name: Build ZIP for HACS

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          cd custom_components/myhome
          zip -r ../../myhome.zip .

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: myhome.zip
